version: '3.8'
services:
  db_auth:
    container_name: db_auth
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: db01
    ports:
      - "54321:5432"
    image: postgres:alpine3.19